### ISSUE TITLE
Fix tests on all platforms

### ISSUE THREAD

**Issue by sharkdp** [sharkdp/argmax#2]
This is the current state (copied from https://github.com/sharkdp/fd/issues/410)

- [x] fix compile errors on all `fd`-supported platforms
  - [x] i686-pc-windows-mscv
  - [x] i686-unknown-linux-gnu
  - [x] i686-unknown-linux-musl
  - [x] x86_64-apple-darwin
  - [x] x86_64-pc-windows-gnu
  - [x] x86_64-pc-windows-mscv
  - [x] x86_64-unknown-linux-gnu
  - [x] x86_64-unknown-linux-musl
- [x] fix unit test on all platforms
  - [x] i686-pc-windows-mscv
  - [x] i686-unknown-linux-gnu
  - [x] i686-unknown-linux-musl
  - [x] x86_64-apple-darwin
  - [x] x86_64-pc-windows-gnu
  - [x] x86_64-pc-windows-mscv
  - [x] x86_64-unknown-linux-gnu
  - [x] x86_64-unknown-linux-musl
- [ ] Make sure that enforced limit is reasonably close* to actual (experimental) limit
  - [x] i686-pc-windows-mscv (679 vs 2045)
  - [x] i686-unknown-linux-gnu (348,906 vs 349,417)
  - [ ] i686-unknown-linux-musl (10,295 vs 349,409)
  - [x] x86_64-apple-darwin (20,585 vs 21,096)
  - [x] x86_64-pc-windows-gnu (679 vs 2045)
  - [x] x86_64-pc-windows-mscv (679 vs 2045)
  - [x] x86_64-unknown-linux-gnu (348,329 vs 348,841)
  - [ ] x86_64-unknown-linux-musl (10,294 vs 349,408)

*reasonably close: it shouldn't be an order of magnitude smaller than the actual limit.

**Comment by tavianator** [comment]
musl just hardcodes `ARG_MAX`:

- https://git.musl-libc.org/cgit/musl/tree/src/conf/sysconf.c?id=b76f37fd5625d038141b52184956fb4b7838e9a5#n187
- https://git.musl-libc.org/cgit/musl/tree/include/limits.h?id=b76f37fd5625d038141b52184956fb4b7838e9a5#n49

Not sure we can do much about that

**Comment by sharkdp** [comment]
Ok, thank you. So let's close this for now and start to work on the integration in `fd`.
